<template>
	<section>
		<v-row class='py-1' justify='center'>
			<v-col cols='12' lg='8' class='py-1'>
				• Ensure you have an authenticator app installed on your cell phone (other authenticator apps are available)
			</v-col>
			<v-col cols='12' lg='8' class='py-1'>
				<v-row align='center' class='ma-0 pa-0' justify='space-around'>
					<v-col
						v-for='(item, index) of appLinks'
						:key='index'
						cols='6'
						class='ma-0 pa-0'
					>
						<a
							:href='item.href'
							rel='noopener noreferrer'
							target='_blank'
						>
							<ActionButton
								:block='true'
								:href='item.href'
								:icon='item.icon'
								:small='true'
								:text='item.platform'
								color='black'
							/>
						</a>
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col cols='12' lg='8' class='py-1'>
				• Use the authenticator app to scan the following QR code (or manually enter the secret)
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col cols='auto' class=' text-center py-1'>
				<QrCode :value='qrCode' :size='size' level='H' render-as='svg'/>
				<v-row class='' justify='center'>
					<v-col cols='auto' class='text-caption'>
						secret: {{ secret }}
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col cols='12' lg='8' class='py-1'>
				• Enter the six digit code generated by the authenticator app into the box below and verify that the code is correct
			</v-col>
		</v-row>
		<v-row justify='center' class=''>
			<v-col cols='12' md='6' class=''>
				<v-text-field
					v-model='userToken'
					@keydown.enter='verify'
					:disabled='loading'
					:density='smAndDown?"compact":"default"'
					:error-messages='errorMessage'
					:prepend-inner-icon='mdiCellphoneInformation'
					class=''
					color='primary'
					label='app generated code'
					variant='outlined'
					required
				/>
			</v-col>
		</v-row>

		<v-row justify='center' class=''>
			<v-col cols='12' md='8' lg='4' class='pa-0 ma-0'>
				<v-row justify='space-around' class='pa-0 ma-0'>
					<v-col cols='6' class='ma-0 pa-0'>
						<ActionButton
							@click='cancel'
							v-model:disabled='loading'
							:icon='mdiClose'
							:block='true'
							:iconFirst='true'
							color='pi'
							text='cancel'
							:small='true'
						/>
					</v-col>
					<v-col cols='6' id='verify-2fa-button' class='ma-0 pa-0'>
						<ActionButton
							@click='verify'
							v-model:disabled='verifyValid'
							:block='true'
							:icon='mdiCheck'
							:small='true'
							color='primary'
							text='verify'
						/>
					</v-col>
				</v-row>
			</v-col>
		</v-row>
	</section>
</template>

<script setup lang='ts'>
import { axios_authenticatedUser } from '@/services/axios';
import { snackError, snackSuccess } from '@/services/snack';
import { useDisplay } from 'vuetify';
import { mdiApple, mdiClose, mdiCheck, mdiCellphoneInformation, mdiGooglePlay } from '@mdi/js';
import ActionButton from '@/components/Buttons/ActionButton.vue';
import QrCode from 'qrcode.vue';

const { mdAndUp, smAndDown } = useDisplay();

onBeforeUnmount(() => {
	cancel();
});
onMounted(() => {
	// Cancel setup after 2 minutes of inacitivy
	setupTimeout.value = setTimeout (() => {
		cancel();
	}, 120 * 1000);
});

const [ settingSectionStore, twoFAStore ] = [ settingSectionModule(), twoFAModule() ];

const loading = computed({
	get (): boolean {
		return loadingModule().loading;
	},
	set (b: boolean): void {
		loadingModule().set_loading(b);
	}
});

const secret = computed((): string => {
	return twoFAStore.secret;
});
const email = computed((): string => {
	return userModule().email;
});
const qrCode = computed((): string => {
	return `otpauth://totp/staticPi:${email.value}?secret=${secret.value}&issuer=staticPi&digits=6&period=30`;
});
const size = computed((): number => {
	return mdAndUp.value ? 200 : 125;
});
const verifyValid = computed((): boolean => {
	return !loading.value && !(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''));
});

const errorMessage = ref('');
const setupTimeout = ref(0);
const userToken = ref('');
const appLinks = [
	{
		href: 'https://apps.apple.com/us/app/microsoft-authenticator/id983156458',
		icon: mdiApple,
		platform: 'iOS'
	},
	{
		href: 'https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US',
		icon: mdiGooglePlay,
		platform: 'android'
	}
];

const cancel = async (): Promise<void> => {
	if (settingSectionStore.current_section) settingSectionStore.set_current_section(undefined);
	await Promise.all([
		axios_authenticatedUser.setupTwoFA_delete(),
		twoFAStore.set_secret(''),
		twoFAStore.set_setupProcessStarted(false)
	]);
	clearTimeout(setupTimeout.value);
};

const verify = async (): Promise<void> => {
	if (!userToken.value) {
		errorMessage.value = 'code required';
		return;
	}
	if (!(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''))) {
		errorMessage.value = 'code invalid';
		return;
	}
	loading.value = true;
	const response = await axios_authenticatedUser.setupTwoFA_post({ token: userToken.value });
	loading.value = false;
	if (response) {
		snackSuccess({ message: 'Two-Factor Authentication activated' });
		settingSectionStore.set_current_section(undefined);
		await axios_authenticatedUser.user_get();
	}
	else {
		errorMessage.value = 'generated code invalid';
		snackError({ message: 'generated code incorrect' });
	}
};
	
watch(userToken, (_i: string): void => {
	if (!(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''))) {
		errorMessage.value = 'code invalid';
		return;
	}
	errorMessage.value = '';
});

</script>