<template>
	<section>
		<v-row class='py-1' justify='center'>
			<v-col class='py-1' cols='12' lg='8'>
				• Ensure you have an authenticator app installed on your cell phone (other authenticator apps are
				available)
			</v-col>
			<v-col class='py-1' cols='12' lg='8'>
				<v-row align='center' class='ma-0 pa-0' justify='space-around'>
					<v-col v-for='(item, index) of appLinks' :key='index' class='ma-0 pa-0' cols='6'>
						<a :href='item.href' rel='noopener noreferrer' target='_blank'>
							<ActionButton
								:block='true'
								color='black'
								:href='item.href'
								:icon='item.icon'
								:small='true'
								:text='item.platform'
							/>
						</a>
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col class='py-1' cols='12' lg='8'>
				• Use the authenticator app to scan the following QR code (or manually enter the secret)
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col class=' text-center py-1' cols='auto'>
				<QrCode level='H' render-as='svg' :size :value='qrCode' />
				<v-row class='' justify='center'>
					<v-col class='text-caption' cols='auto'>
						secret: {{ secret }}
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-1' justify='center'>
			<v-col class='py-1' cols='12' lg='8'>
				• Enter the six digit code generated by the authenticator app into the box below and verify that the
				code is correct
			</v-col>
		</v-row>
		<v-row class='' justify='center'>
			<v-col class='' cols='12' md='6'>
				<v-text-field
					v-model='userToken'
					class=''
					color='primary'
					:density='smAndDown ? "compact" : "default"'
					:disabled='loading'
					:error-messages='errorMessage'
					label='app generated code'
					:prepend-inner-icon='mdiCellphoneInformation'
					required
					variant='outlined'
					@keydown.enter='verify'
				/>
			</v-col>
		</v-row>

		<v-row class='' justify='center'>
			<v-col class='pa-0 ma-0' cols='12' lg='4' md='8'>
				<v-row class='pa-0 ma-0' justify='space-around'>
					<v-col class='ma-0 pa-0' cols='6'>
						<ActionButton
							:block='true'
							color='pi'
							:disabled='loading'
							:icon='mdiClose'
							:icon-first='true'
							:small='true'
							text='cancel'
							@click='cancel'
						/>
					</v-col>
					<v-col id='verify-2fa-button' class='ma-0 pa-0' cols='6'>
						<ActionButton
							:block='true'
							color='primary'
							:disabled='verifyValid'
							:icon='mdiCheck'
							:small='true'
							text='verify'
							@click='verify'
						/>
					</v-col>
				</v-row>
			</v-col>
		</v-row>
	</section>
</template>

<script setup lang='ts'>
import { mdiApple, mdiCellphoneInformation, mdiCheck, mdiClose, mdiGooglePlay } from '@mdi/js'
import QrCode from 'qrcode.vue'
import { useDisplay } from 'vuetify'
import { axios_authenticatedUser } from '@/services/axios'
import { snackError, snackSuccess } from '@/services/snack'

const { mdAndUp, smAndDown } = useDisplay()

onBeforeUnmount(() => {
	cancel()
})
onMounted(() => {
	// Cancel setup after 2 minutes of inacitivy
	setupTimeout.value = setTimeout(() => {
		cancel()
	}, 120 * 1000)
})

const [settingSectionStore, twoFAStore] = [settingSectionModule(), twoFAModule()]

const loading = computed({
	get (): boolean {
		return loadingModule().loading
	},
	set (b: boolean): void {
		loadingModule().set_loading(b)
	},
})

const secret = computed(() => twoFAStore.secret)
const email = computed(() => userModule().email)
const qrCode = computed(() => `otpauth://totp/staticPi:${email.value}?secret=${secret.value}&issuer=staticPi&digits=6&period=30`)
const size = computed(() => mdAndUp.value ? 200 : 125)
const verifyValid = computed(() => !loading.value && !(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, '')))

const errorMessage = ref('')
const setupTimeout = ref(0)
const userToken = ref('')
const appLinks = [
	{
		href: 'https://apps.apple.com/us/app/microsoft-authenticator/id983156458',
		icon: mdiApple,
		platform: 'iOS',
	},
	{
		href: 'https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US',
		icon: mdiGooglePlay,
		platform: 'android',
	},
]

async function cancel (): Promise<void> {
	if (settingSectionStore.current_section) settingSectionStore.set_current_section(undefined)
	await Promise.all([
		axios_authenticatedUser.setupTwoFA_delete(),
		twoFAStore.set_secret(''),
		twoFAStore.set_setupProcessStarted(false),
	])
	clearTimeout(setupTimeout.value)
}

async function verify (): Promise<void> {
	if (!userToken.value) {
		errorMessage.value = 'code required'
		return
	}
	if (!(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''))) {
		errorMessage.value = 'code invalid'
		return
	}
	loading.value = true
	const response = await axios_authenticatedUser.setupTwoFA_post({ token: userToken.value })
	loading.value = false
	if (response) {
		snackSuccess({ message: 'Two-Factor Authentication activated' })
		settingSectionStore.set_current_section(undefined)
		await axios_authenticatedUser.user_get()
	} else {
		errorMessage.value = 'generated code invalid'
		snackError({ message: 'generated code incorrect' })
	}
}

watch(userToken, (_i: string): void => {
	if (!(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''))) {
		errorMessage.value = 'code invalid'
		return
	}
	errorMessage.value = ''
})

</script>
