<template>
	<div>
		Two-Factor Authentication (2FA) is an additional layer of security to protect your <StaticPi /> account.
		When activated, you will be required to enter a time sensitive code during login, and optionally at any other time when your user password is required for authentication.
		<br>This code can be generated by a cell phone app.
		<br>
		<br>
		Enabling Two-Factor Authentication greatly increases the security and safety of your account.
	</div>
</template>

<script setup lang="ts">
</script>
